import type { EffectRecipe } from "../model/types";

const recipe = (
  input: Omit<
    EffectRecipe,
    "forge" | "schemaVersion" | "contentVersion" | "tier" | "themePolicy"
  > &
    Pick<EffectRecipe, "themePolicy">,
): EffectRecipe => ({
  forge: "tileforge-effect-forge",
  schemaVersion: "0.1.0",
  contentVersion: "0.1.0",
  tier: 1,
  ...input,
});

export const INTERNAL_SLICE_RECIPES: EffectRecipe[] = [
  recipe({
    id: "player.accurate-shot",
    seed: "tier1-player-dart-v1",
    class: "projectile",
    allegiance: "player",
    role: "accurate",
    danger: "ordinary",
    material: "physical",
    family: "player-subordinate-v1",
    themePolicy: "identity-locked",
    frame: { w: 12, h: 8, pivot: [5, 4], forward: [1, 0], padding: 2 },
    animation: { frames: 2, frameMs: 80, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "capsule", lengthPx: 5, radiusPx: 1 },
    render: {
      silhouette: "projectile.player-dart",
      treatment: "player-subordinate-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "PLAYER_PROJECTILE",
    audio: [
      {
        id: "sfx.player.accurate_release",
        event: "release",
        spatial: true,
        cooldownMs: 50,
        stackPolicy: "nearest-loudest",
      },
    ],
  }),
  recipe({
    id: "player.spread-pellet",
    seed: "tier1-spread-pellet-v1",
    class: "projectile",
    allegiance: "player",
    role: "spread",
    danger: "ordinary",
    material: "physical",
    family: "player-subordinate-v1",
    themePolicy: "identity-locked",
    frame: { w: 8, h: 8, pivot: [4, 4], forward: [1, 0], padding: 2 },
    animation: { frames: 1, frameMs: 90, loop: false, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "circle", radiusPx: 1 },
    render: {
      silhouette: "projectile.pellet",
      treatment: "player-subordinate-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "PLAYER_PROJECTILE",
    audio: [
      {
        id: "sfx.player.spread_volley",
        event: "release",
        spatial: true,
        cooldownMs: 90,
        stackPolicy: "once-per-volley",
      },
    ],
  }),
  recipe({
    id: "player.pierce-return",
    seed: "tier1-pierce-return-v1",
    class: "projectile",
    allegiance: "player",
    role: "pierce-return",
    danger: "ordinary",
    material: "arcane",
    family: "player-subordinate-v1",
    themePolicy: "identity-locked",
    frame: { w: 16, h: 16, pivot: [8, 8], forward: [1, 0], padding: 2 },
    animation: { frames: 4, frameMs: 90, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "capsule", lengthPx: 9, radiusPx: 2 },
    render: {
      silhouette: "projectile.return-blade",
      treatment: "player-subordinate-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "PLAYER_PROJECTILE",
    audio: [
      {
        id: "sfx.player.pierce_release",
        event: "release",
        spatial: true,
        cooldownMs: 110,
        stackPolicy: "nearest-loudest",
      },
    ],
  }),
  recipe({
    id: "hostile.aimed-dart",
    seed: "tier1-hostile-dart-v1",
    class: "projectile",
    allegiance: "hostile",
    role: "aimed",
    danger: "ordinary",
    material: "physical",
    family: "hostile-hot-core-v1",
    themePolicy: "identity-locked",
    frame: { w: 12, h: 8, pivot: [5, 4], forward: [1, 0], padding: 2 },
    animation: { frames: 2, frameMs: 90, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "capsule", lengthPx: 6, radiusPx: 1 },
    render: {
      silhouette: "projectile.hostile-needle",
      treatment: "hostile-hot-core-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "HOSTILE_PROJECTILE",
    audio: [
      {
        id: "sfx.hostile.aimed_dart_release",
        event: "release",
        spatial: true,
        cooldownMs: 70,
        stackPolicy: "nearest-loudest",
      },
    ],
  }),
  recipe({
    id: "hostile.predictive-orb",
    seed: "tier1-predictive-orb-v1",
    class: "projectile",
    allegiance: "hostile",
    role: "predictive",
    danger: "ordinary",
    material: "arcane",
    family: "hostile-hot-core-v1",
    themePolicy: "identity-locked",
    frame: { w: 12, h: 12, pivot: [6, 6], forward: [1, 0], padding: 2 },
    animation: { frames: 4, frameMs: 80, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "circle", radiusPx: 3 },
    render: {
      silhouette: "projectile.orb",
      treatment: "hostile-hot-core-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "HOSTILE_PROJECTILE",
    audio: [
      {
        id: "sfx.hostile.predictive_orb_release",
        event: "release",
        spatial: true,
        cooldownMs: 70,
        stackPolicy: "nearest-loudest",
      },
    ],
  }),
  recipe({
    id: "hostile.fan-crescent",
    seed: "tier1-fan-crescent-v1",
    class: "projectile",
    allegiance: "hostile",
    role: "fan",
    danger: "ordinary",
    material: "arcane",
    family: "hostile-hot-core-v1",
    themePolicy: "identity-locked",
    frame: { w: 12, h: 12, pivot: [6, 6], forward: [1, 0], padding: 2 },
    animation: { frames: 2, frameMs: 100, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "capsule", lengthPx: 6, radiusPx: 2 },
    render: {
      silhouette: "projectile.crescent",
      treatment: "hostile-hot-core-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "HOSTILE_PROJECTILE",
    audio: [
      {
        id: "sfx.hostile.fan_release",
        event: "release",
        spatial: true,
        cooldownMs: 100,
        stackPolicy: "once-per-volley",
      },
    ],
  }),
  recipe({
    id: "hostile.radial-shard",
    seed: "tier1-radial-shard-v1",
    class: "projectile",
    allegiance: "hostile",
    role: "radial",
    danger: "ordinary",
    material: "arcane",
    family: "hostile-hot-core-v1",
    themePolicy: "identity-locked",
    frame: { w: 8, h: 8, pivot: [4, 4], forward: [1, 0], padding: 2 },
    animation: { frames: 2, frameMs: 90, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "travel-direction", sampling: "nearest" },
    geometry: { shape: "circle", radiusPx: 2 },
    render: {
      silhouette: "projectile.star-shard",
      treatment: "hostile-hot-core-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "HOSTILE_PROJECTILE",
    audio: [
      {
        id: "sfx.hostile.radial_burst",
        event: "release",
        spatial: true,
        cooldownMs: 120,
        stackPolicy: "once-per-volley",
      },
    ],
  }),
  recipe({
    id: "telegraph.prefire-glint",
    seed: "tier1-prefire-glint-v1",
    class: "telegraph",
    allegiance: "hostile",
    role: "prefire",
    danger: "ordinary",
    material: "neutral",
    family: "telegraph-v1",
    themePolicy: "fixed",
    frame: { w: 8, h: 8, pivot: [4, 4], forward: [1, 0], padding: 1 },
    animation: {
      frames: 3,
      frameMs: 90,
      loop: false,
      phasePolicy: "event-controlled",
    },
    rotation: { mode: "none", sampling: "nearest" },
    geometry: { shape: "point" },
    render: {
      silhouette: "socket.glint",
      treatment: "telegraph-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "ACTOR_FEEDBACK",
    audio: [
      {
        id: "sfx.telegraph.shooter_glint",
        event: "prefire.begin",
        spatial: true,
        cooldownMs: 80,
        stackPolicy: "nearest-loudest",
      },
    ],
  }),
  recipe({
    id: "telegraph.delayed-ground",
    seed: "tier1-delayed-ground-v1",
    class: "telegraph",
    allegiance: "hostile",
    role: "delayed-area",
    danger: "ordinary",
    material: "arcane",
    family: "telegraph-v1",
    themePolicy: "identity-locked",
    frame: { w: 32, h: 32, pivot: [16, 16], forward: [1, 0], padding: 1 },
    animation: {
      frames: 4,
      frameMs: 180,
      loop: false,
      phasePolicy: "event-controlled",
    },
    rotation: { mode: "none", sampling: "nearest" },
    geometry: { shape: "circle", radiusPx: 12 },
    render: {
      silhouette: "ground.circle",
      treatment: "telegraph-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "GROUND_TELEGRAPH",
    audio: [
      {
        id: "sfx.telegraph.ground_arm",
        event: "arm",
        spatial: true,
        cooldownMs: 200,
        stackPolicy: "nearest-loudest",
      },
    ],
  }),
  recipe({
    id: "zone.active-ground-hazard",
    seed: "tier1-active-hazard-v1",
    class: "zone",
    allegiance: "hostile",
    role: "active-area",
    danger: "ordinary",
    material: "corruption",
    family: "hazard-v1",
    themePolicy: "identity-locked",
    frame: { w: 32, h: 32, pivot: [16, 16], forward: [1, 0], padding: 1 },
    animation: { frames: 4, frameMs: 130, loop: true, phasePolicy: "spawn-at-zero" },
    rotation: { mode: "none", sampling: "nearest" },
    geometry: { shape: "circle", radiusPx: 12 },
    render: {
      silhouette: "ground.active",
      treatment: "hazard-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "ACTIVE_HAZARD",
    audio: [
      {
        id: "sfx.zone.active_hazard_loop",
        event: "active",
        spatial: true,
        cooldownMs: 300,
        stackPolicy: "one-voice",
      },
    ],
  }),
  recipe({
    id: "feedback.hit-contact",
    seed: "tier1-hit-contact-v1",
    class: "feedback",
    allegiance: "neutral-support",
    role: "flesh-hit",
    danger: "ordinary",
    material: "physical",
    family: "feedback-v1",
    themePolicy: "fixed",
    frame: { w: 12, h: 12, pivot: [6, 6], forward: [1, 0], padding: 2 },
    animation: { frames: 4, frameMs: 55, loop: false, phasePolicy: "event-controlled" },
    rotation: { mode: "impact-normal", sampling: "nearest" },
    geometry: { shape: "point" },
    render: {
      silhouette: "impact.burst",
      treatment: "feedback-hit-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "ACTOR_FEEDBACK",
    audio: [
      {
        id: "sfx.feedback.hit_flesh",
        event: "hit",
        spatial: true,
        cooldownMs: 40,
        stackPolicy: "coalesce",
      },
    ],
  }),
  recipe({
    id: "feedback.blocked-immune",
    seed: "tier1-blocked-v1",
    class: "feedback",
    allegiance: "neutral-support",
    role: "blocked",
    danger: "ordinary",
    material: "neutral",
    family: "feedback-v1",
    themePolicy: "fixed",
    frame: { w: 12, h: 12, pivot: [6, 6], forward: [1, 0], padding: 2 },
    animation: { frames: 4, frameMs: 65, loop: false, phasePolicy: "event-controlled" },
    rotation: { mode: "impact-normal", sampling: "nearest" },
    geometry: { shape: "point" },
    render: {
      silhouette: "impact.chevron",
      treatment: "feedback-block-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "ACTOR_FEEDBACK",
    audio: [
      {
        id: "sfx.feedback.blocked_deflect",
        event: "blocked",
        spatial: true,
        cooldownMs: 80,
        stackPolicy: "coalesce",
      },
    ],
  }),
  recipe({
    id: "feedback.damage-number",
    seed: "tier1-damage-number-v1",
    class: "combat-text",
    allegiance: "neutral-support",
    role: "damage-number",
    danger: "ordinary",
    material: "neutral",
    family: "feedback-v1",
    themePolicy: "fixed",
    frame: { w: 16, h: 8, pivot: [8, 7], forward: [1, 0], padding: 1 },
    animation: { frames: 1, frameMs: 250, loop: false, phasePolicy: "event-controlled" },
    rotation: { mode: "none", sampling: "nearest" },
    geometry: { shape: "point" },
    render: {
      silhouette: "glyph.damage",
      treatment: "combat-text-v1",
      alpha: "binary",
      blend: "normal",
    },
    worldLayer: "COMBAT_TEXT",
    audio: [
      {
        id: "sfx.feedback.damage_number",
        event: "damage",
        spatial: true,
        cooldownMs: 90,
        stackPolicy: "coalesce",
      },
    ],
  }),
];

export const RECIPE_BY_ID = new Map(
  INTERNAL_SLICE_RECIPES.map((entry) => [entry.id, entry]),
);
